version: '2'

services:
    madc:
        image: madc
        container_name: madc
        volumes:
            - /data/mADC/config/flask/:/config
            - /data/mADC/studies/:/studies
        environment:
            - GUNICORN_WORKERS=1
            - CELERY_WORKERS=1
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "5000:5000"  # Port mapping as a list item

networks:
    default:
        external: true
        name: digby_network
